[general]
static=yes
writeprotect=no

[from-local]
exten => 43,1,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => 60,1,Dial(PJSIP/60@hub,30)
 same => n,Hangup()

exten => _900X,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

; 自分以外宛は Hub に投げる
exten => _[12345]XXX,1,Dial(PJSIP/${EXTEN}@hub,30)
 same => n,Hangup()

[from-hub]
exten => _900X,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()