[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=172.20.0.0/24
external_media_address=192.168.0.55
external_signaling_address=192.168.0.55

;================== 参加者 ==================
[site-a]
type=aor
contact=sip:192.168.0.139:5060
qualify_frequency=30

[site-a]
type=endpoint
context=from-sites
disallow=all
allow=ulaw,alaw
aors=site-a
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[site-a]
type=identify
endpoint=site-a
match=192.168.0.139

;================== 運営 ==================
[site-z]
type=aor
contact=sip:172.20.0.20:5060
qualify_frequency=30

[site-z]
type=endpoint
context=from-sites
disallow=all
allow=ulaw,alaw
aors=site-z
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[site-z]
type=identify
endpoint=site-z
match=172.20.0.20