;番号は配布したラズパイの番号に応じて適宜変更してください
;R01 の場合は 1001, 1002, 1003...
;R02 の場合は 2001, 2002, 2003... のような感じです

;TODO: 以下のコンテキスト名は pjsip.conf で指定したものと一致させてください
[コンテキスト名]
; 43番は自分の声が聞こえるかのテスト用です。
exten => 43,1,Answer()
 same => n,Echo()
 same => n,Hangup()

;TODO: 自分の内線番号にマッチするようにパターンを変更してください(例: 1001, _200Xなど)
exten => ここにパターンを入力,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()
