[from-local]
exten => 43,1,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => 60,1,Dial(PJSIP/60@hub,30)
 same => n,Hangup()

exten => _100X,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => _[2345]XXX,1,Dial(PJSIP/${EXTEN}@hub,30)
 same => n,Hangup()

[from-hub]
exten => _100X,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()