[from-local]
exten => 43,1,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => _100X,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => 60,1,Dial(PJSIP/60@hub,30)
 same => n,Hangup()

;自分内線以外宛は Hub に投げる
;TODO: パターンは自分以外の番号にマッチするように変更してください
;ラズパイの番号がR01なら _[23459]XXX、R02なら _[13459]XXXのような感じです
exten => _[2345]XXX,1,Dial(PJSIP/${EXTEN}@hub,30)
 same => n,Hangup()

;Hubからの着信を受け付ける
[from-hub]
;TODO: この部分は必要に応じて変更してください
;ラズパイの番号がR01なら _100X、R02なら _200X のような感じです
exten => _100X,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()