[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

;================== Hub (静的トランク) ==================
[hub]
type=aor
contact=sip:192.168.0.55:5060

[hub]
type=endpoint
context=from-hub
disallow=all
allow=ulaw,alaw
aors=hub

[hub]
type=identify
endpoint=hub
match=192.168.0.55

;================== 内線 1001 ==================
[1001]
type=endpoint
context=from-local
disallow=all
allow=ulaw,alaw
auth=1001
aors=1001

[1001]
type=auth
auth_type=userpass
username=1001
password=pass1001

[1001]
type=aor
max_contacts=1

;================== 内線 1002 ==================
[1002]
type=endpoint
context=from-local
disallow=all
allow=ulaw,alaw
auth=1002
aors=1002

[1002]
type=auth
auth_type=userpass
username=1002
password=pass1002

[1002]
type=aor
max_contacts=1